### PR TITLE
docs(readme): fix typo ('cascade' -> 'cascading')

### PR DESCRIPTION
**Pull request by coopbri**
Fixed minor typo in README; "C" in CSS stands for "Cascading" (https://developer.mozilla.org/en-US/docs/Web/CSS)

### CODE REVIEW

**Comment by typicode** [comment]
Agree, I wanted to emphasize the cascade metaphor. Maybe I'll rewrite. Could you also please change it in ./docs?

**Comment by coopbri** [comment]
I feel that, I'm being pedantic :joy: "Cascade" does make more sense for getting the MistCSS point across. What about

> Cascading Style Sheets (CSS) cascade 🌊 → atomized water forms mist 🌫️ → MistCSS creates pure CSS atomic components 🌬️

or even simpler

> Style sheets cascade 🌊 → atomized water forms mist 🌫️ → MistCSS creates pure CSS atomic components 🌬️


Let me know what you think, and I'll update in `docs` as well

**Comment by typicode** [comment]
Good question, I don't know. Go with the one you prefer and I'll merge :+1:

**Comment by typicode** [comment]
Removed the origin of the name in v0.4, maybe I'll re-add it later :)

**Comment by coopbri** [comment]
Oh completely missed your earlier comment, sounds good!

**Pull request closed without merging**
