### PR TITLE
Feat: add css variable support

### LINKED ISSUE #36: [Feature] : Pass the prop directly to the TailwindCSS
Hi @typicode ,

Thank you for this new library.

I like the idea of generating components from CSS instead of integrating CSS in JS.

Honestly, adding CSS to JS is kind of a mess.

I already started using the library (or tool), however, while I was trying to discover the syntax, an idea came to me and I wanted to share it if it is possible to implement it.

```
@scope (.button) {
  button:scope {
    /* Default style */
    @apply text-base rounded-sm;

    &[data-size='lg'] {
      @apply text-lg;
    }

    &[data-size='sm'] {
      @apply text-sm;
    }

    &[data-danger] {
      @apply bg-red-700 text-white;
    }
  }
}
```
In the code above, yu see that we repeating the prop checking to apply the TailwidCSS, is it possible to make it like this : 

```
@scope (.button) {
  button:scope {
    /* Default style */
    @apply text-base rounded-sm;
    &[data-size]{
     @apply text-[data-size]
     }  
  }
}
```

### LINKED ISSUE #40: Use CSS Vars to allow direct passthrough of tailwind variables
This is a suggestion on how to handle #36 as it sounds pretty interesting.

The way i was thinking of it was to enable the use of something like

```
div:scope {
  --padding: 0;
  padding: var(--padding);

 &[data-padding="--spacing-"] {}

```

which the parser would see this as 

```
type BazProps = {
  children?: ReactNode,
  padding?: string,
} & JSX.IntrinsicElements['p']

export function Baz({ children, padding, ...props }: BazProps) {
  return (
    <p {...props} className="baz" style={{ "--padding": `var(--spacing-${padding})` }>
      {children}
    </p>
  )
}
```

I know its not the prettiest solution but it could work in terms of how simple it is, or maybe we could even remove the need for the &[data-padding] somehow and resolve this value from the --padding var directly e.g.

```
div:scope {
  --padding: var(--spacing-0); <-  default value
  padding: var(--padding);
```

this way we could infer that for padding prop to grab the first half of the assigned ts variable and then concat the prop onto the end.

### PR DESCRIPTION
**Pull request by The-Code-Monkey**
from what i found before doing 

`&[data-size="sm"]` didnt work but `&[data-size='sm']` did so i updated the regex string to support double quotes.

this PR also now adds variable support. Might need a custom css.d.ts file if the as string is not wanted, just due to react not liking inline variables as they are not part of CSSType yet.

fixes #36
fixes #40

### CODE REVIEW

**Comment by The-Code-Monkey** [comment]
@typicode let me know your thoughts and I'll do any tweaks if you want any doing

**Comment by typicode** [comment]
Thanks for the PR. I feel that things with the current codebase are getting quite complex.

I plan to rewrite the parsing code, I think it can be improved. Also, I will re-organize a few things in preparation of other features.

Since tests are passing, I can merge it and release a new version if you need it?

**Comment by The-Code-Monkey** [comment]
@typicode yeah I understand, I did need this, but it's up to you whether to merge something like this now or add it when you rebuild things

**Comment by The-Code-Monkey** [comment]
@typicode any update on this as I have some other things I'd like to suggest but I have built them on top of this pr

**Comment by typicode** [comment]
I'm making good progress, but I'd like to rewrite docs and iron things out before releasing the next version.

**Comment by The-Code-Monkey** [comment]
@typicode of course no worries. The only other thing I came across and fixed was I added a list of html element that don't support child element so I added that logic in.

**Comment by The-Code-Monkey** [comment]
I will wait for your rewrite before trying to add anything else

**Comment by The-Code-Monkey** [comment]
closing due to further work needed.

**Pull request closed without merging**
